on: push
name: "Test something"
jobs:
  test-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: exit 0
      - uses: ./
        if: always()
        with:
          ACTION_NAME: Run test scripts
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  test-failure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - run: exit 1
      - uses: ./
        if: always()
        with:
          ACTION_NAME: Run test scripts
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
